# Generated by Django 4.2.7 on 2023-11-08 02:48

from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(default=uuid.uuid4(), on_delete=django.db.models.deletion.CASCADE, to='discussions.thread'),
            preserve_default=False,
        ),
    ]
