# Generated by Django 4.2.7 on 2023-12-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_remove_tag_post_post_tags_alter_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='discussions.tag'),
        ),
    ]
